version: '3'
services:
  app:
    image: app
    restart: always
    build: .
    ports:
      - "9090:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres:
    image: postgres
    volumes:
      - postgres-volume:/var/lib/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tech_stack_db


volumes:
  postgres-volume:

